import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
// import Form from 'react-bootstrap/Form'
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>{`고객 & 회원 관리카드`}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <form className="row g-3">
          <h1 className={styles.title}>{`고객 & 회원 관리카드`}</h1>
          <div className="d-flex">
            <div className="form-check">
              <input
                className="form-check-input"
                type="radio"
                name="flexRadioDefault"
                id="flexRadioDefault1"
              />
              <label className="form-check-label" for="flexRadioDefault1">
                소매고객
              </label>
            </div>
            <div className="form-check">
              <input
                class="form-check-input"
                type="radio"
                name="flexRadioDefault"
                id="flexRadioDefault2"
                checked
              />
              <label className="form-check-label" for="flexRadioDefault2">
                회원
              </label>
            </div>
          </div>

          <div className="col-md-4">
            <label for="inputEmail4" className="form-label">
              성명
            </label>
            <input type="text" className="form-control" id="inputEmail4" />
          </div>
          <div className="col-md-4">
            <label for="inputPassword4" className="form-label">
              생년월일
            </label>
            <input type="text" className="form-control" id="inputPassword4" />
          </div>
          <div className="col-md-4">
            <label for="inputPassword4" className="form-label">
              회원번호
            </label>
            <input type="text" className="form-control" id="inputPassword4" />
          </div>

          <div className="col-4">
            <label for="inputAddress" className="form-label">
              연락처
            </label>
            <input
              type="phone"
              className="form-control"
              id="inputAddress"
              placeholder="1234 Main St"
            />
          </div>
          <div className="col-8">
            <label for="inputAddress" className="form-label">
              주소
            </label>
            <input
              type="text"
              className="form-control"
              id="inputAddress"
              placeholder="1234 Main St"
            />
          </div>

          <div className="col-md-4">
            <label for="inputEmail4" className="form-label">
              가입일자
            </label>
            <input type="text" className="form-control" id="inputEmail4" />
          </div>
          <div className="col-md-4">
            <label for="inputPassword4" className="form-label">
              직업
            </label>
            <input type="text" className="form-control" id="inputPassword4" />
          </div>
          <div className="col-md-4">
            <label for="inputPassword4" className="form-label">
              성장도
            </label>
            <input type="text" className="form-control" id="inputPassword4" />
          </div>

          <div className="col-8">
            <label for="inputAddress" className="form-label">
              직장
            </label>
            <input type="text" className="form-control" id="inputAddress" />
          </div>
          <div className="col-4">
            <label for="inputAddress" className="form-label">
              전화
            </label>
            <input type="text" className="form-control" id="inputAddress" />
          </div>

          <div className="col-12">
            <label for="inputAddress" className="form-label">
              각종기념일
            </label>
            <div className="d-flex">
              <input type="text" className="form-control" id="inputAddress" />
              <input type="text" className="form-control" id="inputAddress" />
              <input type="text" className="form-control" id="inputAddress" />
            </div>
          </div>

          <div className="col-6">
            <label for="inputAddress" className="form-label">
              가족관계
            </label>
            <input type="text" className="form-control" id="inputAddress" />
          </div>

          <div className="col-6">
            <label for="inputAddress" className="form-label">
              기타
            </label>
            <input type="text" className="form-control" id="inputAddress" />
          </div>

          <div className="col-12">
            <label for="inputAddress" className="form-label">
              사업보조자료전달
            </label>
            <input type="text" className="form-control" id="inputAddress" />
          </div>

          <table class="table">
            <thead>
              <tr>
                <th scope="col">날짜</th>
                <th scope="col">구입제품</th>
                <th scope="col">수량</th>
                <th scope="col">금액</th>
                <th scope="col">총구매액</th>
                <th scope="col">사용의견 및 호응도</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <th scope="row">1</th>
                <td>
                  <input
                    type="text"
                    className="form-control"
                    id="inputAddress"
                  />
                </td>
                <td>
                  <input
                    type="text"
                    className="form-control"
                    id="inputAddress"
                  />
                </td>
                <td>
                  <input
                    type="text"
                    className="form-control"
                    id="inputAddress"
                  />
                </td>
                <td>
                  <input
                    type="text"
                    className="form-control"
                    id="inputAddress"
                  />
                </td>
                <td>
                  <input
                    type="text"
                    className="form-control"
                    id="inputAddress"
                  />
                </td>
              </tr>
            </tbody>
          </table>

          <div className="col-12">
            <button type="submit" className="btn btn-primary">
              기입
            </button>
          </div>
        </form>
      </main>

      <footer className={styles.footer}>
        {/* <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span classNameName={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a> */}
      </footer>
    </div>
  );
}
